//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access
    {
        public int ID { get; set; }
        public string DisplayName { get; set; }
        public string LinkURL { get; set; }
        public string ID1 { get; set; }
        public string ID2 { get; set; }
        public string ProgramID { get; set; }
        public string Class { get; set; }
    }
}
