//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string Owner { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CompanyID { get; set; }
    }
}
