//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    /// <summary>
    /// Company
    /// </summary> 
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class Company
    {
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("iD")]
    	public int ID { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("companyName")]
    	public string CompanyName { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("owner")]
    	public string Owner { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("phone")]
    	public string Phone { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("website")]
    	public string Website { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("createTime")]
    	public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("businessLicence")]
    	public string BusinessLicence { get; set; }
    }
}
