//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    /// <summary>
    /// CustomerOperate
    /// </summary> 
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class CustomerOperate
    {
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("id")]
    	public int Id { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("customerId")]
    	public int CustomerId { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("customerName")]
    	public string CustomerName { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("operatorId")]
    	public int OperatorId { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("operatorName")]
    	public string OperatorName { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("assigneeId")]
    	public int AssigneeId { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("assigneeName")]
    	public string AssigneeName { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("remark")]
    	public string Remark { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("state")]
    	public int State { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("operatorTime")]
    	public System.DateTime OperatorTime { get; set; }
    }
}
