//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerVisit
    {
        public int ID { get; set; }
        public string CustomerID { get; set; }
        public string Sourceform { get; set; }
        public string Sourceemp { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> Visitdate { get; set; }
        public string Visitemp { get; set; }
        public string remark { get; set; }
        public string Status { get; set; }
    }
}
