//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    /// <summary>
    /// Customer
    /// </summary> 
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        /// <summary>
    	/// 
    	/// </summary>
    	public decimal ID { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string Customertype { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string CustomerName { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string CustomerPhone { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string CustomerQQ { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string mail { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string CustomerID { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string HomeAddress { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string Owner { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string contract { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string Status { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string CreateEmp { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string ReturnVisit { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public Nullable<System.DateTime> UpdateDate { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string OM { get; set; }
    }
}
