//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    /// <summary>
    /// Customer
    /// </summary> 
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        /// <summary>
    	/// 
    	/// </summary>
    	public decimal ID { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string CustomerType { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string CustomerName { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string CustomerPhone { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string CustomerQQ { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string Mail { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string IDCard { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string HomeAddress { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string Owner { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string Contract { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string State { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string CreaterID { get; set; }
    }
}
