//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    /// <summary>
    /// CustomerOperate
    /// </summary> 
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    using Newtonsoft.Json;
    
    public partial class CustomerOperate
    {
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("ID")]
    	public int ID { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("CustomerID")]
    	public string CustomerID { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("OperatorID")]
    	public string OperatorID { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("State")]
    	public string State { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("Remark")]
    	public string Remark { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("OperatorTime")]
    	public Nullable<System.DateTime> OperatorTime { get; set; }
    }
}
