//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    /// <summary>
    /// CustomerLog
    /// </summary> 
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLog
    {
        /// <summary>
    	/// 
    	/// </summary>
    	public int ID { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string CustomerID { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string Status { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string Remark { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string EMP { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public Nullable<System.DateTime> LogDate { get; set; }
    }
}
