//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    /// <summary>
    /// Employee
    /// </summary> 
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        /// <summary>
    	/// 
    	/// </summary>
    	public int ID { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string Name { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string Company { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string Team { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string Post { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string Supervisor { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string PhoneNumber { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string QQNumber { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string Status { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public Nullable<System.DateTime> WorkStartDate { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public byte[] Photo { get; set; }
    }
}
