//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public string Team { get; set; }
        public string Post { get; set; }
        public string Supervisor { get; set; }
        public string PhoneNumber { get; set; }
        public string QQNumber { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> WorkStartDate { get; set; }
        public byte[] Photo { get; set; }
    }
}
