//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    /// <summary>
    /// Menu
    /// </summary> 
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class Menu
    {
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("id")]
    	public int Id { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("menuName")]
    	public string MenuName { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("menuUrl")]
    	public string MenuUrl { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("menuId")]
    	public string MenuId { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("menuPid")]
    	public string MenuPid { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("class")]
    	public string Class { get; set; }
    }
}
