//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    /// <summary>
    /// Menu
    /// </summary> 
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    using Newtonsoft.Json;
    
    public partial class Menu
    {
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("ID")]
    	public int ID { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("MenuName")]
    	public string MenuName { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("MenuURL")]
    	public string MenuURL { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("MenuID")]
    	public string MenuID { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("MenuPID")]
    	public string MenuPID { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("Class")]
    	public string Class { get; set; }
    }
}
