//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    /// <summary>
    /// Menu
    /// </summary> 
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        /// <summary>
    	/// 
    	/// </summary>
    	public int ID { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string LinkName { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string LinkURL { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string LinkID { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string LinkPID { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string Class { get; set; }
    }
}
