//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    /// <summary>
    /// Message
    /// </summary> 
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class Message
    {
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("id")]
    	public int Id { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("senderId")]
    	public Nullable<int> SenderId { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("receiverId")]
    	public Nullable<int> ReceiverId { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("subject")]
    	public string Subject { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("content")]
    	public string Content { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("sendTime")]
    	public Nullable<System.DateTime> SendTime { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("state")]
    	public Nullable<int> State { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("num")]
    	public string Num { get; set; }
    }
}
