//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    /// <summary>
    /// Mylog
    /// </summary> 
    using System;
    using System.Collections.Generic;
    
    public partial class Mylog
    {
        /// <summary>
    	/// 
    	/// </summary>
    	public int id { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string emp { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string subject { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string contents { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public Nullable<System.DateTime> createDate { get; set; }
    }
}
