//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    /// <summary>
    /// Team
    /// </summary> 
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class Team
    {
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("id")]
    	public int Id { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("name")]
    	public string Name { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("leader")]
    	public string Leader { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("leaderPhone")]
    	public string LeaderPhone { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("slogan")]
    	public string Slogan { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("companyId")]
    	public string CompanyId { get; set; }
    }
}
