//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    /// <summary>
    /// User
    /// </summary> 
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class User
    {
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("id")]
    	public int Id { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("userName")]
    	public string UserName { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("loginName")]
    	public string LoginName { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("password")]
    	public string Password { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("companyId")]
    	public int CompanyId { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("teamId")]
    	public int TeamId { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("postId")]
    	public int PostId { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("supervisorId")]
    	public int SupervisorId { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("phoneNumber")]
    	public string PhoneNumber { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("workStartDate")]
    	public Nullable<System.DateTime> WorkStartDate { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("photo")]
    	public byte[] Photo { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("state")]
    	public int State { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("isEnable")]
    	public Nullable<bool> IsEnable { get; set; }
    }
}
