//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    /// <summary>
    /// WorkLog
    /// </summary> 
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class WorkLog
    {
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("iD")]
    	public int ID { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("userID")]
    	public int UserID { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("title")]
    	public string Title { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("content")]
    	public string Content { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	[JsonProperty("createTime")]
    	public System.DateTime CreateTime { get; set; }
    }
}
