//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    /// <summary>
    /// WorkLog
    /// </summary> 
    using System;
    using System.Collections.Generic;
    
    public partial class WorkLog
    {
        /// <summary>
    	/// 
    	/// </summary>
    	public int Id { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public Nullable<int> UserId { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string Title { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string Content { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
