//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public decimal ID { get; set; }
        public string Customertype { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerQQ { get; set; }
        public string mail { get; set; }
        public string CustomerID { get; set; }
        public string HomeAddress { get; set; }
        public string Owner { get; set; }
        public string contract { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateEmp { get; set; }
        public string ReturnVisit { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string OM { get; set; }
    }
}
