//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerNoContact
    {
        public int ID { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string phone { get; set; }
        public string QQ { get; set; }
        public string Mail { get; set; }
        public string CompanyOwner { get; set; }
        public Nullable<System.DateTime> ContactDate { get; set; }
        public string EMP { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
    }
}
