//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRiCheng
    {
        public int ID { get; set; }
        public string Subject { get; set; }
        public string richengtime { get; set; }
        public string address { get; set; }
        public string detail { get; set; }
        public string emp { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
